language: python
python:
  - "2.7"
install:
  #- pip install pep8 --use-mirrors
  #- pip install pyflakes --use-mirrors
  - pip install robotframework
  - pip install robotframework-selenium2library
  - pip install selenium
  - pip install decorator
  - pip install docutils
  #- "if [[ ${BROWSER} == 'ie' ]]; then pip install ie_only_pkg; fi"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
script:
  - "pybot --outputdir MyBuild Sample.txt"

after_script:
   - git fetch
   - git remote
   - git status
   - git add .
   - git commit -m 'Reports are ready'
  #- git config --global user.email "ur@gmail.com"
  #- git config --global user.name "u"
  #- git add /home/travis/build/uranjeeth/MyBuild/log.html
  #- git commit -m 'Reports are ready'
  #- git config --global push.default matching
  #- cat /home/travis/build/uranjeeth/Project-1/log.html

notifications:
  email:
    #- ur@gmail.com 
env:
  matrix:
  - BROWSER=firefox
  #- BROWSER=ie # will be added when we have completed SauceLabs CI
  #- BROWSER=safari # will be added after #247 merged
